language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install qtdeclarative5-dev qtbase5-private-dev qtdeclarative5-private-dev libqt5opengl5-dev qtdeclarative5-qtquick2-plugin
script: 
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make
