language: cpp
compiler:
  - gcc
# Change this to your needs
before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt54
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential qt54creator
script: 
    - "/opt/qt54/bin/qmake" ./Alluvial.pro -r -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug
    - make
