language: cpp
compiler:
  - gcc
# Change this to your needs
before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt54-trusty
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential qt54creator
script: 
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make
