language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt52-qmake qtbase52-dev qtdeclarative52-dev libqt52webkit5-dev libsqlite3-dev build-essential
script: 
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - qmake -qt+=qml
    - make
